Added Factory Class + Changed Difficulty Enums
drofp/MyRPS pull request #32
Opened 2019-03-08 03:14 UTC by evanugarte

closes #27

2019-03-13 20:15 UTC, drofp requested changes
Looks pretty good! Just need to change quick naming thing

2019-03-13 20:15 UTC, drofp commented on include/setting_option.h
> +  D_RANDOM,
Please use `camelCased` with 'k' preface for enum naming, [per the style guide](https://google.github.io/styleguide/cppguide.html#Enumerator_Names), and [precedence set in previously named enums](https://github.com/drofp/MyRPS/blob/master/include/move.h)

2019-03-13 20:15 UTC, drofp commented on src/chooser_factory.cpp
> +    return new MLChooser();
Will likely change after merging #34, but that can be resolved in a later issue.

2019-03-14 21:43 UTC, drofp commented on include/setting_option.h
> +  D_RANDOM,
done

2019-03-14 21:43 UTC, drofp commented on src/chooser_factory.cpp
> +    return new MLChooser();
will resolve in #36

2019-03-14 21:43 UTC, drofp approved these changes

2019-03-14 21:44 UTC, evanugarte commented
I didn't do this

2019-03-14 21:44 UTC, merged